---
- name: install oracle database on linux
  hosts: "{{ var1 }}"
  remote_user: root
  gather_facts: no
  tasks:
    - name: installing pre-requisites for database
      script: /demo/1-db-pre.sh 

    - name: installing oracle database  
      script: /demo/2-db-ins.sh
      become: yes
      become_user: oracle

    - name: post scripts for database installation
      script: /demo/3-db-post-root.sh
      become: yes
      become_user: root

    - name: post scripts for database installation
      script: /demo/4-db-post-oracle.sh
      become: yes
      become_user: oracle
