---
- name: install and start Apache
  hosts: "{{ var1 }}"
  remote_user: linux
  gather_facts: no
  hosts: "{{ var1 }}"
  tasks:
    - name: install Apache on Solaris
      pkg5: name=web/server/apache-24
      become: yes
      become_method: sudo
      become_user: root

