---
- name: install and start Nginx
  hosts: localhost
  remote_user: root
  gather_facts: no
  tasks:
    - name: Download sources
      file:
          path: /root/tested_file
          state: touch
          owner: root
          group: root
          mode: 01777
