---
- name: test playbook
  hosts: localhost
  remote_user: root
  gather_facts: no
  tasks:
    - name: create a file
      file:
          path: /root/tested_file
          state: touch
          owner: root
          group: root
          mode: 01777
