---
- name: Install AD Services feature
  hosts: windows
  gather_facts: no
  tasks:
    - name: configure AD
      win_feature:
        name: AD-Domain-Services
        include_management_tools: yes
        include_sub_features: yes
        state: present
      register: result
    - name: create new forest
      win_domain:
        dns_domain_name: example.com
        safe_mode_password: P@ssw0rd
      register: result
    - name: Reboot After creation
      win_reboot:
         msg: "Server config in progess; reboot...."
      when: result.reboot_required
